### PR TITLE
Massage Chef12HomebrewUser.find_homebrew_uid into username

### PR DESCRIPTION
**Pull request by kbruner**
Fixes https://github.com/opscode-cookbooks/homebrew/issues/71

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by kbruner** [comment]
Trying to get an issue with my supermarket account fixed, but in the meantime, I think this qualifies under [The Obvious Fix Rule](http://docs.chef.io/community_contributions.html#the-obvious-fix-rule)

**Comment by kbruner** [comment]
CLA signed!

**Comment by trinitronx** [comment]
Tested out this pull request on OS X Yosemite (10.10.3) and can confirm it fixes #71.  Tested with Chef version `12.3.0`

**Comment by chilicheech** [comment]
Folks, when can we get this merged and released? This cookbook in non-functional on chef 12.3.0 without this fix.

**Comment by hiremaga** [comment]
Big +1. Is there anything we might do to help get this merged?

**Comment by jtimberman** [comment]
Does it continue to work on versions > 12.0.0 < 12.3.0? Does it work on Chef 11?

**Comment by hiremaga** [comment]
IIRC the conditional on [homebrew_mixin.rb:31](https://github.com/kbruner/homebrew/blob/issue71/libraries/homebrew_mixin.rb#L31) flows to [line 39](https://github.com/kbruner/homebrew/blob/issue71/libraries/homebrew_mixin.rb#L39) on Chef 12.0.3 (and Chef 11). I believe this is why we've been able to workaround this issue by downgrading and locking to either Chef 12.0.3 or Chef 11.

**Comment by treyhyde** [comment]
this patch put us back in business, thanks

**Pull request merged**
